-- Identity. Everything else in this phase hangs off it: the leaderboard stops
-- keying on whatever name somebody typed, and online play needs to know who is
-- in a room.
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stored as the player typed it, so their name appears the way they wrote
    -- it. Uniqueness is enforced on the folded form below, or Sam and sam
    -- would be two accounts nobody could tell apart on a leaderboard.
    username VARCHAR(32) NOT NULL,
    username_folded VARCHAR(32) NOT NULL,
    -- BCrypt output is 60 characters. The column is wider so that changing the
    -- algorithm later does not need a migration.
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_accounts_username_folded UNIQUE (username_folded)
);
