-- A logged-in player, until they log out or it expires.
CREATE TABLE account_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    -- The token's hash, not the token. Anyone who reads this table gets the
    -- same thing they get from the password column: something they cannot use.
    -- SHA-256 is enough here, unlike for passwords: a 256-bit random token has
    -- nothing to guess at, so there is no dictionary to slow down.
    token_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_session_token UNIQUE (token_hash),
    CONSTRAINT fk_session_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

-- Every request with a token looks a session up by its hash, so that lookup
-- should not be a table scan.
CREATE INDEX idx_session_expires ON account_sessions (expires_at);
