-- An online game, from the moment somebody creates a room until it is played
-- out or expires.
--
-- The game itself is kept as JSON rather than spread across columns: it is
-- already a GameSnapshot, the same shape a saved local game uses, and the
-- server has no reason to query inside it. What is a column is what the server
-- decides with — who may act, whether it is still open, when it dies.
CREATE TABLE game_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Six characters, typed by a human off another screen. Unique so that two
    -- rooms cannot answer to the same code.
    code VARCHAR(6) NOT NULL,
    host_account_id BIGINT NOT NULL,
    guest_account_id BIGINT,
    status VARCHAR(20) NOT NULL,
    -- The GameSnapshot, once there is a game. Null while a room is waiting for
    -- somebody to join.
    --
    -- TEXT rather than CLOB. H2 accepts both; PostgreSQL has no CLOB type at
    -- all, so the original spelling built the whole rooms table on H2 and
    -- failed outright on the database this is deployed to. TEXT is what both
    -- understand, and it is unbounded on PostgreSQL, which a snapshot needs.
    game_state TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- Three clocks live here as one column: whatever the current state's
    -- deadline is. A room nobody joins dies soonest, because creating one and
    -- walking away is the cheapest way to hold a code and a row for ever.
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_room_code UNIQUE (code),
    CONSTRAINT fk_room_host
        FOREIGN KEY (host_account_id) REFERENCES accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_room_guest
        FOREIGN KEY (guest_account_id) REFERENCES accounts (id) ON DELETE SET NULL
);

-- The sweep deletes by expiry, and it is the rows nobody reads that pile up.
CREATE INDEX idx_room_expires ON game_rooms (expires_at);
-- Capping open rooms per account means counting them per account.
CREATE INDEX idx_room_host ON game_rooms (host_account_id, status);
