-- Which moves have already been applied.
--
-- A client sends a move, the response is lost on the way back, and the client
-- retries because from where it is sitting nothing happened. Without this the
-- question is asked twice, the turn passes twice, and the game is wrong in a
-- way neither player can explain.
--
-- The key comes from the client and is unique per move, so a retry carries the
-- same one and the second attempt changes nothing.
CREATE TABLE room_move_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code VARCHAR(6) NOT NULL,
    move_key VARCHAR(64) NOT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- Scoped to the room rather than global: two players in different games
    -- generating the same key is nobody's problem but their own room's.
    CONSTRAINT uq_move_key UNIQUE (room_code, move_key)
);

-- Cleared with the room it belongs to, by the same sweep.
CREATE INDEX idx_move_key_room ON room_move_keys (room_code);
