CREATE TABLE game_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    winner VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE game_result_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_result_id BIGINT NOT NULL,
    play_order INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    selected_character VARCHAR(255) NOT NULL,
    CONSTRAINT fk_participant_game_result
        FOREIGN KEY (game_result_id) REFERENCES game_results (id) ON DELETE CASCADE,
    CONSTRAINT uq_participant_play_order UNIQUE (game_result_id, play_order)
);

CREATE TABLE game_result_question_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL,
    question_order INTEGER NOT NULL,
    question VARCHAR(2000) NOT NULL,
    answer BOOLEAN NOT NULL,
    CONSTRAINT fk_question_answer_participant
        FOREIGN KEY (participant_id) REFERENCES game_result_participants (id) ON DELETE CASCADE,
    CONSTRAINT uq_question_answer_order UNIQUE (participant_id, question_order)
);
